config/routes.rb
Rails.application.routes.draw do
  get 'catalog', to: 'catalog#index'

  get 'admin', to: 'admin#index'

  resources :gifts

  resources :occasions do
    member do
      get :add_gift
      get :send_gift
    end
  end

  resources :recipients

  resources :accounts

  devise_for :users

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :user
        can :manage, Account, :user_id => user.id
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/gift.rb
class Gift < ActiveRecord::Base
	has_many :gift_occasions
	has_many :occasions, through: :gift_occasions

	mount_uploader :picture, GiftPictureUploader

	extend FriendlyId
	friendly_id :name, use: :slugged

	acts_as_taggable
end

app/models/gift_occasion.rb
class GiftOccasion < ActiveRecord::Base
  belongs_to :gift
  belongs_to :occasion
end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  belongs_to :recipient
  has_many :gift_occasions
	has_many :gifts, through: :gift_occasions

	def self.future
		where('date >= ?', Date.today)
	end

	def self.order_by_date
		order(date: :desc)
	end

	def self.unsent
		where(sent: nil)
	end
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :user
  has_many :occasions

  accepts_nested_attributes_for :occasions
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
	has_one :account
	has_many :recipients

	before_create :add_default_role

	def add_default_role
		self.add_role :user
	end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	authorize! :update, Gift
  	@gifts = Gift.paginate(:page => params[:page], :per_page => 3)
  	@accounts = Account.all
  	@future_occasions = Occasion.order_by_date.future.unsent
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
	skip_before_action :authenticate_user!
  def index
  	if params[:tag]
  		@gifts = Gift.tagged_with(params[:tag])
  	else
  		@gifts = Gift.all
  	end
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to admin_path, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:name, :description, :price, :picture, :tag_list)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>Admin</h1>

<div class="row">
	<div class="col-md-6">
		<h2>Gifts (<%= @gifts.count %>)</h2>
		<%= link_to 'Add gift', new_gift_path, class: 'btn btn-primary btn-sm' %>
		<table class="table">
			<tr>
				<th>Name</th>
				<th>Price</th>
			</tr>
			<% @gifts.each do |gift| %>
				<tr>
					<td><%= image_tag(gift.picture_url(:thumbnail), width: 50, height: 50) %> 
					<%= link_to gift.name, gift %></td>
					<td><%= gift.price %></td>
				</tr>
			<% end %>
		</table>
		<%= will_paginate @gifts %>
	</div>

	<div class="col-md-6">
		<h2>Accounts (<%= @accounts.count %>)</h2>
		<table class="table">
			<tr>
				<td>Account name</td>
				<td>Email</td>
			</tr>
				<% @accounts.each do |account| %>
			<tr>
					<td><%= account.name %></td>
					<td><%= account.user.email %></td>
			</tr>
				<% end %>
		</table>

	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h2>Upcoming orders  (<%= @future_occasions.count %>)</h2>
		<table class="table">
			<tr>
				<th>Order number</th>
				<th>Date to be sent</th>
				<th>Gifts to be sent</th>
				<th>Sent</th>
			</tr>
			<% @future_occasions.each do |occasion| %>
				<tr>
					<td><%= occasion.id %></td>
					<td><%= occasion.date %></td>
					<td>
						<ul>
							<% occasion.gifts.each do |gift| %>
								<li><%= gift.name %></li>
							<% end %>
						</ul>
					</td>
					<td><%= link_to 'Sent', send_gift_occasion_path(occasion), class: 'btn btn-info' %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/catalog">Gifts</a></li>

        <% if user_signed_in? %>
          <% if current_user.has_role? :admin %>
            <li><a href="/admin">Admin</a></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.account.name if current_user.account %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% if current_user.account %>
                <li><a href="<%= account_path(current_user.account) %>">My account</a></li>
              <% else %>
                <li><a href="/accounts/new">Create account</a></li>
              <% end %>
              
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autogiftr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<style>
body {
	padding-top: 60px;
}
</style>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
<%= yield %>
</div>

</body>
</html>