config/routes.rb
Rails.application.routes.draw do
  get 'catalog', to: 'catalog#index'

  get 'admin', to: 'admin#index'

  resources :gifts

  resources :occasions do
    member do
      get :add_gift
      get :send_gift
    end
  end

  resources :recipients

  resources :accounts

  devise_for :users

  root 'welcome#index'

end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :user
  has_many :occasions

  accepts_nested_attributes_for :occasions
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)
    @recipient.user = current_user

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to account_path(@recipient.user.account), notice: 'Recipient was successfully created.' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:name, :address, :user_id, occasions_attributes: [:id, :name, :date, :message, :occastion_type])
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<%= simple_nested_form_for(@recipient) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, input_html: { class: 'form-control' } %>
    <%= f.input :address, input_html: { class: 'form-control' } %>
  </div>

  <p><strong>Add occasions</strong></p>

  
		  <%= f.fields_for :occasions do |occasion_field| %>
		  	<%= occasion_field.input :name %>
		  	<%= occasion_field.input :occastion_type, collection: ['Birthday', 'Anniversary', 'Valentines', 'Other'] %>
		  	<%= occasion_field.input :date %>
		  	<%= occasion_field.input :message %>
		  	<%= occasion_field.link_to_remove "Remove this occasion" %>
		  <% end %>
  	<%= f.link_to_add "Add occasion", :occasions %>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>Editing recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<h1>Listing recipients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipients.each do |recipient| %>
      <tr>
        <td><%= recipient.name %></td>
        <td><%= recipient.address %></td>
        <td><%= recipient.user %></td>
        <td><%= link_to 'Show', recipient %></td>
        <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
        <td><%= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipient', new_recipient_path %>

app/views/recipients/new.html.erb
<h1>New recipient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipient.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @recipient.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipient.user %>
</p>

<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Back', recipients_path %>