config/routes.rb
Rails.application.routes.draw do
  get 'catalog', to: 'catalog#index'

  get 'admin', to: 'admin#index'

  resources :gifts

  resources :occasions do
    member do
      get :add_gift
      get :send_gift
    end
  end

  resources :recipients

  resources :accounts

  devise_for :users

  root 'welcome#index'

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  belongs_to :recipient
  has_many :gift_occasions
	has_many :gifts, through: :gift_occasions

	def self.future
		where('date >= ?', Date.today)
	end

	def self.order_by_date
		order(date: :desc)
	end

	def self.unsent
		where(sent: nil)
	end
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  before_action :set_occasion, only: [:send_gift, :add_gift, :show, :edit, :update, :destroy]

  def send_gift
    @occasion.update_column('sent', true)
    DeliveryNotificationMailer.notify(@occasion).deliver
    redirect_to :back
  end


  def add_gift
    if params[:gift]
      @occasion.gifts << Gift.find(params[:gift])
    end
    redirect_to :back
  end
  # GET /occasions
  # GET /occasions.json
  def index
    @occasions = Occasion.all
  end

  # GET /occasions/1
  # GET /occasions/1.json
  def show
    @gifts = Gift.all
  end

  # GET /occasions/new
  def new
    if params[:recipient]
      @recipient = Recipient.find(params[:recipient])
    end
    @occasion = Occasion.new
  end

  # GET /occasions/1/edit
  def edit
  end

  # POST /occasions
  # POST /occasions.json
  def create
    @occasion = Occasion.new(occasion_params)

    respond_to do |format|
      if @occasion.save
        format.html { redirect_to @occasion, notice: 'Occasion was successfully created.' }
        format.json { render :show, status: :created, location: @occasion }
      else
        format.html { render :new }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occasions/1
  # PATCH/PUT /occasions/1.json
  def update
    respond_to do |format|
      if @occasion.update(occasion_params)
        format.html { redirect_to @occasion, notice: 'Occasion was successfully updated.' }
        format.json { render :show, status: :ok, location: @occasion }
      else
        format.html { render :edit }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occasions/1
  # DELETE /occasions/1.json
  def destroy
    @occasion.destroy
    respond_to do |format|
      format.html { redirect_to occasions_url, notice: 'Occasion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occasion
      @occasion = Occasion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occasion_params
      params.require(:occasion).permit(:message, :name, :date, :occastion_type, :recipient_id)
    end
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/_form.html.erb
<%= simple_form_for(@occasion) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Name of occasion' %>
    <%= f.input :occastion_type, label: 'Type of occasion', collection: ['Birthday', 'Anniversary', 
      'Valentines', 'Religious holiday'] %>
    <%= f.input :message %>
    <%= f.input :date %>
    <%= f.input :recipient_id, input_html: { value: @recipient.id }, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/occasions/edit.html.erb
<h1>Editing occasion</h1>

<%= render 'form' %>

<%= link_to 'Show', @occasion %> |
<%= link_to 'Back', occasions_path %>

app/views/occasions/index.html.erb
<h1>Listing occasions</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Name</th>
      <th>Date</th>
      <th>Occastion type</th>
      <th>Recipient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @occasions.each do |occasion| %>
      <tr>
        <td><%= occasion.message %></td>
        <td><%= occasion.name %></td>
        <td><%= occasion.date %></td>
        <td><%= occasion.occastion_type %></td>
        <td><%= occasion.recipient %></td>
        <td><%= link_to 'Show', occasion %></td>
        <td><%= link_to 'Edit', edit_occasion_path(occasion) %></td>
        <td><%= link_to 'Destroy', occasion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Occasion', new_occasion_path %>

app/views/occasions/new.html.erb
<h1>New occasion <%= 'for ' + @recipient.name if @recipient %></h1>

<%= render 'form' %>

<%= link_to 'Back', occasions_path %>

app/views/occasions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @occasion.message %>
</p>

<p>
  <strong>Name:</strong>
  <%= @occasion.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @occasion.date %>
</p>

<p>
  <strong>Occastion type:</strong>
  <%= @occasion.occastion_type %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @occasion.recipient %>
</p>

<h2>Gifts selected</h2>
<ul>
  <% if @occasion.gifts.count > 0 %>
    <% @occasion.gifts.each do |gift| %>
      <li><%= gift.name %></li>
    <% end %>
  <% end %>
</ul>

<hr>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
  </tr>
  <% @gifts.each do |gift| %>
    <tr>
      <td><%= gift.name %></td>
      <td><%= gift.price %></td>
      <td><%= link_to 'Add gift', add_gift_occasion_path(gift: gift.id), class: 'btn btn-primary' %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Edit', edit_occasion_path(@occasion) %> |
<%= link_to 'Back', occasions_path %>