config/routes.rb
Rails.application.routes.draw do
  get 'catalog', to: 'catalog#index'

  get 'admin', to: 'admin#index'

  resources :gifts

  resources :occasions do
    member do
      get :add_gift
      get :send_gift
    end
  end

  resources :recipients

  resources :accounts

  devise_for :users

  root 'welcome#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    authorize! :manage, @account
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user = current_user

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :address, :phone, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.address %></td>
        <td><%= account.phone %></td>
        <td><%= account.user %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @account.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @account.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.user.email %>
</p>

<p><%= link_to 'Add a recipient', new_recipient_path, class: 'btn btn-danger' %>

 | <%= link_to 'Edit', edit_account_path(@account), class: 'btn btn-default' %>

</p>


<h2>My recipients</h2>
<table class="table table-hover">
<tr>
	<th>Name</th>
	<th>Address</th>
	<th>Occasions</th>
	<th></th>
</tr>
<% @account.user.recipients.each do |recipient| %>
	<tr>
		<td><%= recipient.name %></td>
		<td><%= recipient.address %></td>
		<td>
			<% if recipient.occasions.count > 0 %>
				<% recipient.occasions.each do |occasion| %>
					<%= link_to occasion.name, occasion %><br>
				<% end %>
			<% end %>
		</td>
		<td><%= link_to 'Add occasion', new_occasion_path(recipient: recipient.id), class: 'btn btn-primary' %></td>
	</tr>
<% end %>
</table>